version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "cgc"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "cgc/tf"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "dkdf"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "dkdf/tf"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "cgc/tf"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "cgc/pt"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "cgc/cf"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "dkdf/tf"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "dkdf/pt"
    schedule:
      interval: "daily"
