name: bld

on:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  blds:
    strategy:
      matrix:
        registry: ["ghcr.io", "docker"]
        subject: ["cgc", "dkdf"]
        container: ["pt", "tf"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        if: ${{ strategy.registry == 'docker' }}
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        if: ${{ strategy.registry == 'ghcr.io' }}
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.subject }}/${{ matrix.container }}.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.subject }}:${{ matrix.container }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.subject }}:buildcache-${{ matrix.container }}
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.subject }}:buildcache-${{ matrix.container }},mode=max
