name: cgc_rel

on:
  release:
    types: [published]

  schedule:
    - cron: '0 0 * * *'

  pull_request:
    branches: [ main ]

jobs:

  dockerrel:

    strategy:
      matrix:
        subject: ["cgc", "dkdf"]
        container: ["pt", "tf", "jx"]
  
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.subject }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.subject }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.subject }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.subject }}:buildcache,mode=max


  ghcrrel:

    strategy:
      matrix:
        subject: ["cgc", "dkdf"]
        container: ["pt", "tf", "jx"]
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.subject }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/ngam/${{ matrix.subject }}:latest
          cache-from: type=registry,ref=ghcr.io/ngam/${{ matrix.subject }}:buildcache
          cache-to: type=registry,ref=ghcr.io/ngam/${{ matrix.subject }}:buildcache,mode=max
