name: cgc_rel

on:
  release:
    types: [published]

jobs:

  dockerrel:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: cgc/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cgc:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/cgc:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/cgc:buildcache,mode=max

  ghcrrel:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/cgc

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: cgc/Dockerfile
          push: true
          tags: ghcr.io/ngam/cgc:latest
          cache-from: type=registry,ref=ghcr.io/ngam/cgc:buildcache
          cache-to: type=registry,ref=ghcr.io/ngam/cgc:buildcache,mode=max
