name: foam

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'foam/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file foam/Dockerfile
